# Generated by Django 2.0.13 on 2019-06-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_auto_20190603_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulepreference',
            name='preference_type',
            field=models.IntegerField(),
        ),
    ]
