# Generated by Django 2.0.13 on 2019-06-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_auto_20190603_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomprivilege',
            name='privilege_level',
            field=models.IntegerField(),
        ),
    ]
