# Generated by Django 2.0.13 on 2019-06-10 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_auto_20190603_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_slots', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student Type Name')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.StudentType'),
        ),
        migrations.AddField(
            model_name='schedulerequirement',
            name='student_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.StudentType'),
        ),
        migrations.AddField(
            model_name='schedulerequirement',
            name='term_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.RoomTerm'),
        ),
    ]
