# Generated by Django 2.0.13 on 2019-06-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_auto_20190611_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferenceoption',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
