# Generated by Django 2.0.13 on 2019-06-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_auto_20190611_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenceoption',
            name='color_coding',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
