# Generated by Django 2.0.13 on 2019-06-13 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_preferenceoption_color_coding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulerequirement',
            name='term_id',
        ),
        migrations.AddField(
            model_name='schedulerequirement',
            name='room_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scheduling.Room'),
            preserve_default=False,
        ),
    ]
