# Generated by Django 2.0.13 on 2019-06-15 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_auto_20190613_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomprivilege',
            name='privilege_level',
        ),
    ]
